# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 1000

# Inserts a blank line between shell prompts
add_newline = true

# Disable the package module, hiding it from the prompt completely
#[package]
#disabled = true

[kubernetes]
disabled = true

[package]
disabled = true

[scala]
disabled = true
